// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Wordifly
{
        public const string achievement_master_of_words = "CgkI8oqxqZ4JEAIQGQ"; // <GPGSID>
        public const string achievement_thats_big = "CgkI8oqxqZ4JEAIQDw"; // <GPGSID>
        public const string achievement_tenacious = "CgkI8oqxqZ4JEAIQCg"; // <GPGSID>
        public const string achievement_so_chute = "CgkI8oqxqZ4JEAIQFA"; // <GPGSID>
        public const string achievement_you_are_the_best = "CgkI8oqxqZ4JEAIQBA"; // <GPGSID>
        public const string achievement_wordifly = "CgkI8oqxqZ4JEAIQDA"; // <GPGSID>
        public const string achievement_dont_ask_you_dad = "CgkI8oqxqZ4JEAIQEA"; // <GPGSID>
        public const string achievement_nailed_it = "CgkI8oqxqZ4JEAIQFw"; // <GPGSID>
        public const string achievement_century = "CgkI8oqxqZ4JEAIQEg"; // <GPGSID>
        public const string achievement_high_5 = "CgkI8oqxqZ4JEAIQBQ"; // <GPGSID>
        public const string achievement_triplet = "CgkI8oqxqZ4JEAIQAg"; // <GPGSID>
        public const string achievement_firefly = "CgkI8oqxqZ4JEAIQCw"; // <GPGSID>
        public const string achievement_trio = "CgkI8oqxqZ4JEAIQCQ"; // <GPGSID>
        public const string achievement_watery_eyes = "CgkI8oqxqZ4JEAIQGA"; // <GPGSID>
        public const string achievement_thats_wasnt_possible = "CgkI8oqxqZ4JEAIQEw"; // <GPGSID>
        public const string achievement_quinquagenarian = "CgkI8oqxqZ4JEAIQEQ"; // <GPGSID>
        public const string achievement_silver_jubilee = "CgkI8oqxqZ4JEAIQDQ"; // <GPGSID>
        public const string achievement_wordified = "CgkI8oqxqZ4JEAIQAQ"; // <GPGSID>
        public const string achievement_you_got_teased = "CgkI8oqxqZ4JEAIQBg"; // <GPGSID>
        public const string achievement_more_than_3 = "CgkI8oqxqZ4JEAIQAw"; // <GPGSID>
        public const string achievement_double_century = "CgkI8oqxqZ4JEAIQFQ"; // <GPGSID>
        public const string leaderboard_top_score_makers = "CgkI8oqxqZ4JEAIQBw"; // <GPGSID>
        public const string achievement_mouth_wide_open = "CgkI8oqxqZ4JEAIQFg"; // <GPGSID>
        public const string achievement_superstar = "CgkI8oqxqZ4JEAIQDg"; // <GPGSID>

}

